name: Setup
description: Setup the current job

inputs:
  jdk:
    description: JDK to setup
    required: true

  ruby:
    description: Ruby version to setup
    required: false
    default: 2.7

  cache-version:
    description: Version of the caches
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java & Scala
      uses: coursier/setup-action@v1
      with:
        jvm: ${{ inputs.jdk }}
        apps: sbtn sbt

    - name: Restore cache
      uses: coursier/cache-action@v6
      with:
        extraKey: ${{ inputs.cache-version }}

    - name: Setup graphviz
      run: sudo apt install -y graphviz
      shell: bash

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: ${{ inputs.cache-version }}

    - name: Setup Jekyll
      run: |
        bundler bin jekyll
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
      shell: bash
