queue_rules:
  - name: default
    conditions:
      - status-success=CI (ubuntu-latest, temurin:1.17)
      - status-success=CI (ubuntu-latest, graalvm-java21:21.0.2)

pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - base=main
      - author=scala-steward
    actions:
      queue:
        name: default
        method: squash
        update_method: merge
