queue_rules:
  - name: merge scala-steward's PRs
    queue_conditions:
      - base=main
      - author=scala-steward
    merge_conditions:
      - status-success=CI (ubuntu-latest, temurin:1.17)
      - status-success=CI (ubuntu-latest, graalvm-java21:21.0.2)
    update_method: merge
    merge_method: squash
    autoqueue: true
