queue_rules:
  - name: default
    conditions:
      - status-success=Build and Test (ubuntu-latest, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, graalvm-ce-java11@20.3.0)

pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - base=main
      - author=scala-steward
    actions:
      queue:
        name: default
        method: squash
        update_method: merge
