queue_rules:
  - name: default
    conditions:
      - status-success=Build and Test (ubuntu-latest, temurin:1.17)
      - status-success=Build and Test (ubuntu-latest, graalvm-java17:22.3.0)

pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - base=main
      - author=scala-steward
    actions:
      queue:
        name: default
        method: squash
        update_method: merge
