queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - author=scala-steward
    merge_conditions:
      - status-success=CI (ubuntu-latest, temurin:1.17)
      - status-success=CI (ubuntu-latest, graalvm-java21:21.0.2)
    merge_method: squash
    update_method: merge

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
