language: scala

os:
- linux

sudo: required

services:
- docker

script:
- ./sbt clean +test
- ./sbt "project microsite" makeMicrosite

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache/coursier

install:
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install ruby_dep -v 1.3.1
- gem install public_suffix -v 3.0.3
- gem install jekyll -v 4.0.0
- sudo apt-get update && sudo apt install -y graphviz

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/target/site
  on:
    branch: master
