language: scala

os:
- linux

sudo: required

services:
- docker

script:
- ./sbt +test
- ./sbt "project microsite" makeMicrosite

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

install:
- rvm use 2.2.5 --install --fuzzy
- gem update --system
- gem install sass
- gem install ruby_dep -v 1.3.1
- gem install jekyll -v 3.4.3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/target/site
  on:
    branch: master