name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk:
          - temurin:1.17
          - graalvm-java21:21.0.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup/
        with:
          jdk: ${{ matrix.jdk }}
          ruby: 2.7
          cache-version: v1

      - name: Compile
        run: sbtn +Test/compile

      - name: Linting
        run: sbtn scalafmtCheckAll

      - name: Build the microsite
        run: sbtn microsite/makeMicrosite

      - name: Tests
        run: sbtn +test
